require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CategoriaController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Categorium. As you add validations to Categorium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CategoriaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all categoria as @categoria" do
      categorium = Categorium.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:categoria)).to eq([categorium])
    end
  end

  describe "GET show" do
    it "assigns the requested categorium as @categorium" do
      categorium = Categorium.create! valid_attributes
      get :show, {:id => categorium.to_param}, valid_session
      expect(assigns(:categorium)).to eq(categorium)
    end
  end

  describe "GET new" do
    it "assigns a new categorium as @categorium" do
      get :new, {}, valid_session
      expect(assigns(:categorium)).to be_a_new(Categorium)
    end
  end

  describe "GET edit" do
    it "assigns the requested categorium as @categorium" do
      categorium = Categorium.create! valid_attributes
      get :edit, {:id => categorium.to_param}, valid_session
      expect(assigns(:categorium)).to eq(categorium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Categorium" do
        expect {
          post :create, {:categorium => valid_attributes}, valid_session
        }.to change(Categorium, :count).by(1)
      end

      it "assigns a newly created categorium as @categorium" do
        post :create, {:categorium => valid_attributes}, valid_session
        expect(assigns(:categorium)).to be_a(Categorium)
        expect(assigns(:categorium)).to be_persisted
      end

      it "redirects to the created categorium" do
        post :create, {:categorium => valid_attributes}, valid_session
        expect(response).to redirect_to(Categorium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved categorium as @categorium" do
        post :create, {:categorium => invalid_attributes}, valid_session
        expect(assigns(:categorium)).to be_a_new(Categorium)
      end

      it "re-renders the 'new' template" do
        post :create, {:categorium => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested categorium" do
        categorium = Categorium.create! valid_attributes
        put :update, {:id => categorium.to_param, :categorium => new_attributes}, valid_session
        categorium.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested categorium as @categorium" do
        categorium = Categorium.create! valid_attributes
        put :update, {:id => categorium.to_param, :categorium => valid_attributes}, valid_session
        expect(assigns(:categorium)).to eq(categorium)
      end

      it "redirects to the categorium" do
        categorium = Categorium.create! valid_attributes
        put :update, {:id => categorium.to_param, :categorium => valid_attributes}, valid_session
        expect(response).to redirect_to(categorium)
      end
    end

    describe "with invalid params" do
      it "assigns the categorium as @categorium" do
        categorium = Categorium.create! valid_attributes
        put :update, {:id => categorium.to_param, :categorium => invalid_attributes}, valid_session
        expect(assigns(:categorium)).to eq(categorium)
      end

      it "re-renders the 'edit' template" do
        categorium = Categorium.create! valid_attributes
        put :update, {:id => categorium.to_param, :categorium => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested categorium" do
      categorium = Categorium.create! valid_attributes
      expect {
        delete :destroy, {:id => categorium.to_param}, valid_session
      }.to change(Categorium, :count).by(-1)
    end

    it "redirects to the categoria list" do
      categorium = Categorium.create! valid_attributes
      delete :destroy, {:id => categorium.to_param}, valid_session
      expect(response).to redirect_to(categoria_url)
    end
  end

end
